directory = new Object()
directory['af'] = new Object()
directory['am'] = new Object()
directory['am']['accessibility.html'] = true
directory['am']['documentation.html'] = true
directory['am']['evolution.html'] = true
directory['am']['firefox.html'] = true
directory['am']['ltsp.html'] = true
directory['am']['openoffice.html'] = true
directory['am']['welcome.html'] = true
directory['ar'] = new Object()
directory['ar']['accessibility.html'] = true
directory['ar']['documentation.html'] = true
directory['ar']['evolution.html'] = true
directory['ar']['firefox.html'] = true
directory['ar']['ltsp.html'] = true
directory['ar']['openoffice.html'] = true
directory['ar']['welcome.html'] = true
directory['ast'] = new Object()
directory['ast']['accessibility.html'] = true
directory['ast']['documentation.html'] = true
directory['ast']['evolution.html'] = true
directory['ast']['firefox.html'] = true
directory['ast']['ltsp.html'] = true
directory['ast']['openoffice.html'] = true
directory['ast']['welcome.html'] = true
directory['az'] = new Object()
directory['az']['accessibility.html'] = true
directory['be'] = new Object()
directory['be']['accessibility.html'] = true
directory['be']['documentation.html'] = true
directory['be']['evolution.html'] = true
directory['be']['firefox.html'] = true
directory['be']['ltsp.html'] = true
directory['be']['openoffice.html'] = true
directory['be']['welcome.html'] = true
directory['bg'] = new Object()
directory['bg']['accessibility.html'] = true
directory['bg']['documentation.html'] = true
directory['bg']['evolution.html'] = true
directory['bg']['firefox.html'] = true
directory['bg']['ltsp.html'] = true
directory['bg']['openoffice.html'] = true
directory['bg']['welcome.html'] = true
directory['bn'] = new Object()
directory['bn']['accessibility.html'] = true
directory['bn']['documentation.html'] = true
directory['bn']['evolution.html'] = true
directory['bn']['firefox.html'] = true
directory['bn']['ltsp.html'] = true
directory['bn']['openoffice.html'] = true
directory['bn']['welcome.html'] = true
directory['br'] = new Object()
directory['br']['accessibility.html'] = true
directory['br']['documentation.html'] = true
directory['br']['evolution.html'] = true
directory['br']['firefox.html'] = true
directory['br']['ltsp.html'] = true
directory['br']['openoffice.html'] = true
directory['br']['welcome.html'] = true
directory['bs'] = new Object()
directory['bs']['accessibility.html'] = true
directory['bs']['documentation.html'] = true
directory['bs']['firefox.html'] = true
directory['bs']['openoffice.html'] = true
directory['bs']['welcome.html'] = true
directory['ca'] = new Object()
directory['ca']['accessibility.html'] = true
directory['ca']['documentation.html'] = true
directory['ca']['evolution.html'] = true
directory['ca']['firefox.html'] = true
directory['ca']['ltsp.html'] = true
directory['ca']['openoffice.html'] = true
directory['ca']['welcome.html'] = true
directory['ckb'] = new Object()
directory['ckb']['documentation.html'] = true
directory['ckb']['welcome.html'] = true
directory['cs'] = new Object()
directory['cs']['accessibility.html'] = true
directory['cs']['documentation.html'] = true
directory['cs']['evolution.html'] = true
directory['cs']['firefox.html'] = true
directory['cs']['ltsp.html'] = true
directory['cs']['openoffice.html'] = true
directory['cs']['welcome.html'] = true
directory['csb'] = new Object()
directory['csb']['accessibility.html'] = true
directory['csb']['documentation.html'] = true
directory['csb']['evolution.html'] = true
directory['csb']['firefox.html'] = true
directory['csb']['ltsp.html'] = true
directory['csb']['openoffice.html'] = true
directory['csb']['welcome.html'] = true
directory['cv'] = new Object()
directory['cv']['welcome.html'] = true
directory['cy'] = new Object()
directory['cy']['accessibility.html'] = true
directory['cy']['documentation.html'] = true
directory['da'] = new Object()
directory['da']['accessibility.html'] = true
directory['da']['documentation.html'] = true
directory['da']['evolution.html'] = true
directory['da']['firefox.html'] = true
directory['da']['ltsp.html'] = true
directory['da']['openoffice.html'] = true
directory['da']['welcome.html'] = true
directory['de'] = new Object()
directory['de']['accessibility.html'] = true
directory['de']['documentation.html'] = true
directory['de']['evolution.html'] = true
directory['de']['firefox.html'] = true
directory['de']['ltsp.html'] = true
directory['de']['openoffice.html'] = true
directory['de']['welcome.html'] = true
directory['dv'] = new Object()
directory['dv']['documentation.html'] = true
directory['dv']['welcome.html'] = true
directory['el'] = new Object()
directory['el']['accessibility.html'] = true
directory['el']['documentation.html'] = true
directory['el']['evolution.html'] = true
directory['el']['firefox.html'] = true
directory['el']['ltsp.html'] = true
directory['el']['openoffice.html'] = true
directory['el']['welcome.html'] = true
directory['en_AU'] = new Object()
directory['en_AU']['accessibility.html'] = true
directory['en_AU']['documentation.html'] = true
directory['en_AU']['evolution.html'] = true
directory['en_AU']['firefox.html'] = true
directory['en_AU']['ltsp.html'] = true
directory['en_AU']['openoffice.html'] = true
directory['en_AU']['welcome.html'] = true
directory['en_CA'] = new Object()
directory['en_CA']['accessibility.html'] = true
directory['en_CA']['documentation.html'] = true
directory['en_CA']['evolution.html'] = true
directory['en_CA']['firefox.html'] = true
directory['en_CA']['ltsp.html'] = true
directory['en_CA']['openoffice.html'] = true
directory['en_CA']['welcome.html'] = true
directory['en_GB'] = new Object()
directory['en_GB']['accessibility.html'] = true
directory['en_GB']['documentation.html'] = true
directory['en_GB']['evolution.html'] = true
directory['en_GB']['firefox.html'] = true
directory['en_GB']['ltsp.html'] = true
directory['en_GB']['openoffice.html'] = true
directory['en_GB']['welcome.html'] = true
directory['eo'] = new Object()
directory['eo']['accessibility.html'] = true
directory['eo']['documentation.html'] = true
directory['eo']['evolution.html'] = true
directory['eo']['firefox.html'] = true
directory['eo']['ltsp.html'] = true
directory['eo']['openoffice.html'] = true
directory['eo']['welcome.html'] = true
directory['es'] = new Object()
directory['es']['accessibility.html'] = true
directory['es']['documentation.html'] = true
directory['es']['evolution.html'] = true
directory['es']['firefox.html'] = true
directory['es']['ltsp.html'] = true
directory['es']['openoffice.html'] = true
directory['es']['welcome.html'] = true
directory['et'] = new Object()
directory['et']['accessibility.html'] = true
directory['et']['documentation.html'] = true
directory['et']['evolution.html'] = true
directory['et']['firefox.html'] = true
directory['et']['ltsp.html'] = true
directory['et']['openoffice.html'] = true
directory['et']['welcome.html'] = true
directory['eu'] = new Object()
directory['eu']['accessibility.html'] = true
directory['eu']['documentation.html'] = true
directory['eu']['evolution.html'] = true
directory['eu']['ltsp.html'] = true
directory['eu']['openoffice.html'] = true
directory['eu']['welcome.html'] = true
directory['fa'] = new Object()
directory['fa_AF'] = new Object()
directory['fi'] = new Object()
directory['fi']['accessibility.html'] = true
directory['fi']['documentation.html'] = true
directory['fi']['evolution.html'] = true
directory['fi']['firefox.html'] = true
directory['fi']['ltsp.html'] = true
directory['fi']['openoffice.html'] = true
directory['fi']['welcome.html'] = true
directory['fil'] = new Object()
directory['fo'] = new Object()
directory['fr'] = new Object()
directory['fr']['accessibility.html'] = true
directory['fr']['documentation.html'] = true
directory['fr']['evolution.html'] = true
directory['fr']['firefox.html'] = true
directory['fr']['ltsp.html'] = true
directory['fr']['openoffice.html'] = true
directory['fr']['welcome.html'] = true
directory['fy'] = new Object()
directory['fy']['accessibility.html'] = true
directory['fy']['documentation.html'] = true
directory['fy']['ltsp.html'] = true
directory['fy']['welcome.html'] = true
directory['gl'] = new Object()
directory['gl']['accessibility.html'] = true
directory['gl']['documentation.html'] = true
directory['gl']['evolution.html'] = true
directory['gl']['firefox.html'] = true
directory['gl']['ltsp.html'] = true
directory['gl']['openoffice.html'] = true
directory['gl']['welcome.html'] = true
directory['gu'] = new Object()
directory['he'] = new Object()
directory['he']['accessibility.html'] = true
directory['he']['documentation.html'] = true
directory['he']['evolution.html'] = true
directory['he']['firefox.html'] = true
directory['he']['ltsp.html'] = true
directory['he']['openoffice.html'] = true
directory['he']['welcome.html'] = true
directory['hi'] = new Object()
directory['hi']['evolution.html'] = true
directory['hi']['firefox.html'] = true
directory['hi']['ltsp.html'] = true
directory['hr'] = new Object()
directory['hr']['accessibility.html'] = true
directory['hr']['documentation.html'] = true
directory['hr']['evolution.html'] = true
directory['hr']['firefox.html'] = true
directory['hr']['ltsp.html'] = true
directory['hr']['openoffice.html'] = true
directory['hr']['welcome.html'] = true
directory['ht'] = new Object()
directory['hu'] = new Object()
directory['hu']['accessibility.html'] = true
directory['hu']['documentation.html'] = true
directory['hu']['evolution.html'] = true
directory['hu']['firefox.html'] = true
directory['hu']['ltsp.html'] = true
directory['hu']['openoffice.html'] = true
directory['hu']['welcome.html'] = true
directory['id'] = new Object()
directory['id']['accessibility.html'] = true
directory['id']['documentation.html'] = true
directory['id']['evolution.html'] = true
directory['id']['firefox.html'] = true
directory['id']['ltsp.html'] = true
directory['id']['openoffice.html'] = true
directory['id']['welcome.html'] = true
directory['ig'] = new Object()
directory['inh'] = new Object()
directory['is'] = new Object()
directory['is']['accessibility.html'] = true
directory['is']['documentation.html'] = true
directory['is']['evolution.html'] = true
directory['is']['firefox.html'] = true
directory['is']['ltsp.html'] = true
directory['is']['openoffice.html'] = true
directory['is']['welcome.html'] = true
directory['it'] = new Object()
directory['it']['accessibility.html'] = true
directory['it']['documentation.html'] = true
directory['it']['evolution.html'] = true
directory['it']['firefox.html'] = true
directory['it']['ltsp.html'] = true
directory['it']['openoffice.html'] = true
directory['it']['welcome.html'] = true
directory['ja'] = new Object()
directory['ja']['accessibility.html'] = true
directory['ja']['welcome.html'] = true
directory['kk'] = new Object()
directory['kk']['accessibility.html'] = true
directory['kk']['documentation.html'] = true
directory['kk']['evolution.html'] = true
directory['kk']['firefox.html'] = true
directory['kk']['ltsp.html'] = true
directory['kk']['openoffice.html'] = true
directory['kk']['welcome.html'] = true
directory['kn'] = new Object()
directory['kn']['accessibility.html'] = true
directory['kn']['documentation.html'] = true
directory['kn']['firefox.html'] = true
directory['kn']['openoffice.html'] = true
directory['kn']['welcome.html'] = true
directory['ko'] = new Object()
directory['ko']['accessibility.html'] = true
directory['ko']['documentation.html'] = true
directory['ko']['evolution.html'] = true
directory['ko']['firefox.html'] = true
directory['ko']['ltsp.html'] = true
directory['ko']['openoffice.html'] = true
directory['ko']['welcome.html'] = true
directory['ku'] = new Object()
directory['ku']['accessibility.html'] = true
directory['ku']['welcome.html'] = true
directory['la'] = new Object()
directory['lo'] = new Object()
directory['lt'] = new Object()
directory['lt']['accessibility.html'] = true
directory['lt']['documentation.html'] = true
directory['lt']['evolution.html'] = true
directory['lt']['firefox.html'] = true
directory['lt']['ltsp.html'] = true
directory['lt']['openoffice.html'] = true
directory['lt']['welcome.html'] = true
directory['lv'] = new Object()
directory['lv']['accessibility.html'] = true
directory['lv']['documentation.html'] = true
directory['lv']['evolution.html'] = true
directory['lv']['firefox.html'] = true
directory['lv']['ltsp.html'] = true
directory['lv']['openoffice.html'] = true
directory['lv']['welcome.html'] = true
directory['mk'] = new Object()
directory['ml'] = new Object()
directory['ml']['accessibility.html'] = true
directory['ml']['documentation.html'] = true
directory['mn'] = new Object()
directory['mn']['accessibility.html'] = true
directory['mn']['documentation.html'] = true
directory['mn']['evolution.html'] = true
directory['mn']['firefox.html'] = true
directory['mn']['openoffice.html'] = true
directory['mr'] = new Object()
directory['ms'] = new Object()
directory['ms']['accessibility.html'] = true
directory['ms']['documentation.html'] = true
directory['ms']['evolution.html'] = true
directory['ms']['firefox.html'] = true
directory['ms']['ltsp.html'] = true
directory['ms']['openoffice.html'] = true
directory['ms']['welcome.html'] = true
directory['nb'] = new Object()
directory['nb']['accessibility.html'] = true
directory['nb']['documentation.html'] = true
directory['nb']['evolution.html'] = true
directory['nb']['firefox.html'] = true
directory['nb']['ltsp.html'] = true
directory['nb']['openoffice.html'] = true
directory['nb']['welcome.html'] = true
directory['nds'] = new Object()
directory['ne'] = new Object()
directory['ne']['accessibility.html'] = true
directory['nl'] = new Object()
directory['nl']['accessibility.html'] = true
directory['nl']['documentation.html'] = true
directory['nl']['evolution.html'] = true
directory['nl']['firefox.html'] = true
directory['nl']['ltsp.html'] = true
directory['nl']['openoffice.html'] = true
directory['nl']['welcome.html'] = true
directory['nn'] = new Object()
directory['nn']['accessibility.html'] = true
directory['nn']['documentation.html'] = true
directory['nn']['evolution.html'] = true
directory['nn']['firefox.html'] = true
directory['nn']['ltsp.html'] = true
directory['nn']['openoffice.html'] = true
directory['nn']['welcome.html'] = true
directory['oc'] = new Object()
directory['oc']['accessibility.html'] = true
directory['oc']['documentation.html'] = true
directory['oc']['evolution.html'] = true
directory['oc']['firefox.html'] = true
directory['oc']['ltsp.html'] = true
directory['oc']['openoffice.html'] = true
directory['oc']['welcome.html'] = true
directory['om'] = new Object()
directory['om']['documentation.html'] = true
directory['om']['welcome.html'] = true
directory['pa'] = new Object()
directory['pl'] = new Object()
directory['pl']['accessibility.html'] = true
directory['pl']['documentation.html'] = true
directory['pl']['evolution.html'] = true
directory['pl']['firefox.html'] = true
directory['pl']['ltsp.html'] = true
directory['pl']['openoffice.html'] = true
directory['pl']['welcome.html'] = true
directory['ps'] = new Object()
directory['pt'] = new Object()
directory['pt']['accessibility.html'] = true
directory['pt']['documentation.html'] = true
directory['pt']['evolution.html'] = true
directory['pt']['firefox.html'] = true
directory['pt']['ltsp.html'] = true
directory['pt']['openoffice.html'] = true
directory['pt']['welcome.html'] = true
directory['pt_BR'] = new Object()
directory['pt_BR']['accessibility.html'] = true
directory['pt_BR']['documentation.html'] = true
directory['pt_BR']['evolution.html'] = true
directory['pt_BR']['firefox.html'] = true
directory['pt_BR']['ltsp.html'] = true
directory['pt_BR']['openoffice.html'] = true
directory['pt_BR']['welcome.html'] = true
directory['ro'] = new Object()
directory['ro']['accessibility.html'] = true
directory['ro']['documentation.html'] = true
directory['ro']['evolution.html'] = true
directory['ro']['firefox.html'] = true
directory['ro']['ltsp.html'] = true
directory['ro']['openoffice.html'] = true
directory['ro']['welcome.html'] = true
directory['ru'] = new Object()
directory['ru']['accessibility.html'] = true
directory['ru']['documentation.html'] = true
directory['ru']['evolution.html'] = true
directory['ru']['firefox.html'] = true
directory['ru']['ltsp.html'] = true
directory['ru']['openoffice.html'] = true
directory['ru']['welcome.html'] = true
directory['si'] = new Object()
directory['si']['documentation.html'] = true
directory['si']['evolution.html'] = true
directory['si']['firefox.html'] = true
directory['si']['ltsp.html'] = true
directory['si']['openoffice.html'] = true
directory['si']['welcome.html'] = true
directory['sk'] = new Object()
directory['sk']['accessibility.html'] = true
directory['sk']['documentation.html'] = true
directory['sk']['evolution.html'] = true
directory['sk']['firefox.html'] = true
directory['sk']['ltsp.html'] = true
directory['sk']['openoffice.html'] = true
directory['sk']['welcome.html'] = true
directory['sl'] = new Object()
directory['sl']['accessibility.html'] = true
directory['sl']['documentation.html'] = true
directory['sl']['evolution.html'] = true
directory['sl']['firefox.html'] = true
directory['sl']['ltsp.html'] = true
directory['sl']['openoffice.html'] = true
directory['sl']['welcome.html'] = true
directory['sn'] = new Object()
directory['sn']['accessibility.html'] = true
directory['sn']['documentation.html'] = true
directory['sn']['welcome.html'] = true
directory['sq'] = new Object()
directory['sq']['accessibility.html'] = true
directory['sq']['documentation.html'] = true
directory['sq']['evolution.html'] = true
directory['sq']['firefox.html'] = true
directory['sq']['ltsp.html'] = true
directory['sq']['openoffice.html'] = true
directory['sq']['welcome.html'] = true
directory['sr'] = new Object()
directory['sr']['accessibility.html'] = true
directory['sr']['documentation.html'] = true
directory['sr']['evolution.html'] = true
directory['sr']['firefox.html'] = true
directory['sr']['ltsp.html'] = true
directory['sr']['openoffice.html'] = true
directory['sr']['welcome.html'] = true
directory['sv'] = new Object()
directory['sv']['accessibility.html'] = true
directory['sv']['documentation.html'] = true
directory['sv']['evolution.html'] = true
directory['sv']['firefox.html'] = true
directory['sv']['ltsp.html'] = true
directory['sv']['openoffice.html'] = true
directory['sv']['welcome.html'] = true
directory['ta'] = new Object()
directory['te'] = new Object()
directory['te']['accessibility.html'] = true
directory['te']['documentation.html'] = true
directory['te']['evolution.html'] = true
directory['te']['firefox.html'] = true
directory['te']['ltsp.html'] = true
directory['te']['openoffice.html'] = true
directory['te']['welcome.html'] = true
directory['tet'] = new Object()
directory['tet']['documentation.html'] = true
directory['th'] = new Object()
directory['th']['accessibility.html'] = true
directory['th']['documentation.html'] = true
directory['th']['evolution.html'] = true
directory['th']['firefox.html'] = true
directory['th']['ltsp.html'] = true
directory['th']['openoffice.html'] = true
directory['th']['welcome.html'] = true
directory['tl'] = new Object()
directory['tr'] = new Object()
directory['tr']['accessibility.html'] = true
directory['tr']['documentation.html'] = true
directory['tr']['evolution.html'] = true
directory['tr']['firefox.html'] = true
directory['tr']['ltsp.html'] = true
directory['tr']['openoffice.html'] = true
directory['tr']['welcome.html'] = true
directory['ug'] = new Object()
directory['uk'] = new Object()
directory['uk']['accessibility.html'] = true
directory['uk']['documentation.html'] = true
directory['uk']['evolution.html'] = true
directory['uk']['firefox.html'] = true
directory['uk']['ltsp.html'] = true
directory['uk']['welcome.html'] = true
directory['ur'] = new Object()
directory['vi'] = new Object()
directory['vi']['accessibility.html'] = true
directory['vi']['documentation.html'] = true
directory['vi']['evolution.html'] = true
directory['vi']['firefox.html'] = true
directory['vi']['ltsp.html'] = true
directory['vi']['openoffice.html'] = true
directory['vi']['welcome.html'] = true
directory['zh_CN'] = new Object()
directory['zh_CN']['accessibility.html'] = true
directory['zh_CN']['documentation.html'] = true
directory['zh_CN']['evolution.html'] = true
directory['zh_CN']['firefox.html'] = true
directory['zh_CN']['ltsp.html'] = true
directory['zh_CN']['openoffice.html'] = true
directory['zh_CN']['welcome.html'] = true
directory['zh_HK'] = new Object()
directory['zh_HK']['accessibility.html'] = true
directory['zh_HK']['documentation.html'] = true
directory['zh_HK']['evolution.html'] = true
directory['zh_HK']['firefox.html'] = true
directory['zh_HK']['ltsp.html'] = true
directory['zh_HK']['openoffice.html'] = true
directory['zh_HK']['welcome.html'] = true
directory['zh_TW'] = new Object()
directory['zh_TW']['accessibility.html'] = true
directory['zh_TW']['documentation.html'] = true
directory['zh_TW']['evolution.html'] = true
directory['zh_TW']['firefox.html'] = true
directory['zh_TW']['ltsp.html'] = true
directory['zh_TW']['openoffice.html'] = true
directory['zh_TW']['welcome.html'] = true
